### ISSUE TITLE
Shooting myself

### ISSUE THREAD

**Issue by kybernetikos** [justinmimbs/rs-asteroids#1]
This is totally awesome.  I love the way the asteroids break along the line you shoot.

The issue I spotted is that if I shoot directly up, it wraps around the screen and kills me.  I'm using firefox developer 77.0b1

**Comment by justinmimbs** [comment]
Thanks! I'm glad you're enjoying it.

This is intentional, as avoiding shooting yourself is part of the game. You can use your shields to protect yourself from blasts. Try firing directly up and then holding down `S` to see this in action. :smile:
